spring.application.name=agent
spring.config.import=optional:file:.env[.properties]
server.port=8081

spring.ai.ollama.base-url=http://ollama.java21.net
spring.ai.ollama.chat.options.model=qwen2.5:3b-instruct-q4_K_M
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=qwen3:4b-q4_K_M
spring.ai.ollama.chat.options.temperature=0.0
spring.ai.ollama.chat.options.max-tokens=1024

spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
spring.ai.google.genai.api-key=${GEMINI_KEY}
spring.ai.google.genai.chat.options.temperature=0.0

# Tool 실행 로그
logging.level.org.springframework.ai= debug
logging.level.com.nhnacademy.agent= debug

#mcp
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.sse.connections.library-mcp.url=http://localhost:8082/sse
spring.ai.mcp.client.request-timeout=60000
