spring.application.name=ai-library-team3-batch
spring.config.import=optional:file:.env[.properties]

# ===============================
# Datasource (DBCP2)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/team3-library?stringtype=unspecified
spring.datasource.username=team3
spring.datasource.password=5IQCFmyhKvVu8Zvx

spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=1000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Google Gemini \uC124\uC815
# ===============================

# RAG
ai.rag.api-key=${RAG_GEMINI_API_KEY}
ai.rag.model=gemini-2.5-flash-lite
ai.rag.temperature=0.3
ai.rag.top-k=5

# Review
ai.review.api-key=${REVIEW_GEMINI_API_KEY}
ai.review.model=gemini-3.1-flash-lite
ai.review.temperature=0.2
ai.review.max-output-tokens=2048
ai.review.top-p=0.6
ai.review.top-k=20

# ===============================
# Ollama
# ===============================
#spring.ai.ollama.base-url=http://ollama.java21.net
#spring.ai.ollama.chat.options.model=llama3-korean-blossom
#local \uC124\uC815
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:1.5b
spring.ai.ollama.chat.options.temperature=0.3
# Ollama \uD0C0\uC784\uC544\uC6C3 \uC124\uC815 (\uCD08 \uB2E8\uC704)
# Ollama \uC11C\uBC84 \uC751\uB2F5\uC774 \uB290\uB9B4 \uACBD\uC6B0 \uD0C0\uC784\uC544\uC6C3 \uC99D\uAC00
spring.ai.ollama.chat.options.duration=300
spring.ai.ollama.init.timeout=300
spring.ai.ollama.chat.options.top-k=5

# \uC0AC\uC6A9\uD560 \uBAA8\uB378 \uC120\uD0DD (gemini \uB610\uB294 ollama)
spring.ai.selected-model=gemini

# Redis Settings
# Redis \uC124\uC815\uC774 \uC788\uC73C\uBA74 RedisConfig\uAC00 \uC790\uB3D9\uC73C\uB85C \uD65C\uC131\uD654\uB429\uB2C8\uB2E4
spring.data.redis.host=220.67.216.14
spring.data.redis.port=6379
spring.data.redis.password=*N2vya7H@muDTwdNMR!
#spring.data.redis.database=43

# \uC784\uBCA0\uB529 API \uC124\uC815
spring.ai.openai.base-url=https://emb.java21.net
spring.ai.openai.api-key=dummy
spring.ai.openai.embedding.options.model=bge-m3

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=s4.java21.net
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=nhnacademy123!

spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=15
spring.rabbitmq.listener.simple.acknowledge-mode=auto

rabbitmq.queue.review-summary=team3-nhnacademy-library-review
rabbitmq.exchange=team3-nhnacademy-library-exchange
rabbitmq.routing-key=review.summary


