spring.application.name=mcp
spring.config.import=optional:file:.env[.properties], classpath:naru.properties
server.port=8082

# mcp server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=library-mcp
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.type=sync

# mcp client가 sse 연결을 맺는 url
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
