naru.base-url=http://data4library.kr/api
naru.authKey=${LIBRARY_AUTH_KEY}

naru.library-search=/libSrch
naru.book-search=/srchBooks
naru.library-search-by-book=/libSrchByBook
naru.popularity-book-search=/loanItemSrch
naru.book-exist=/bookExist
naru.monthly-keyword=/monthlyKeywords
